// Command genpalettes generates internal/palette/data.go from the
// ColorLisa reference dataset in docs/reference/colorlisa-palettes.md.
// Run from the repo root: go run ./tools/genpalettes
package main

import (
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
)

var rowRe = regexp.MustCompile("^\\| `([a-z0-9-]+)` \\| ([^|]+) \\| ((?:`#[0-9A-Fa-f]{6}` ?){5})\\|$")

func main() {
	src, err := os.ReadFile("docs/reference/colorlisa-palettes.md")
	if err != nil {
		log.Fatal(err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by tools/genpalettes from docs/reference/colorlisa-palettes.md; DO NOT EDIT.\n\n")
	b.WriteString("package palette\n\n")
	b.WriteString("var palettes = []Palette{\n")

	count := 0
	for _, line := range strings.Split(string(src), "\n") {
		m := rowRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		slug, source := m[1], strings.TrimSpace(m[2])
		artist, work := source, ""
		if a, w, found := strings.Cut(source, " — "); found {
			artist, work = a, w
		}
		var hexes []string
		for _, h := range strings.Fields(m[3]) {
			hexes = append(hexes, fmt.Sprintf("MustHex(%q)", strings.Trim(h, "`")))
		}
		fmt.Fprintf(&b, "\t{Slug: %q, Artist: %q, Work: %q,\n\t\tColors: []Color{%s}},\n",
			slug, artist, work, strings.Join(hexes, ", "))
		count++
	}
	b.WriteString("}\n")

	if count < 100 {
		log.Fatalf("parsed only %d palettes; markdown format drifted?", count)
	}
	if err := os.WriteFile("internal/palette/data.go", []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote internal/palette/data.go with %d palettes\n", count)
}
