const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
const baseURL='http://'+(process.env.ART_BROWSER_ADDR||'127.0.0.1:8280');
async function enter(page){const start=page.url();for(let attempt=0;attempt<3;attempt++){const next=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/explorations');await page.getByRole('button',{name:'Create four images'}).click();const response=await next;if(response.status()!==429){expect(response.status()).toBeLessThan(400);return;}await new Promise(resolve=>setTimeout(resolve,Number(response.headers()['retry-after'])*1000));await page.goto(start);}throw Error('Admission did not recover');}
async function four(page){await expect(page.locator('.samples .sample img')).toHaveCount(4,{timeout:60000});await expect.poll(()=>page.locator('.samples .sample img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0)),{timeout:15000}).toBe(true);}
test('four images lead to detail, native file sharing, real download and one-parent similarity',async({page,context})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError')}}));
 await page.goto('/');expect(await context.cookies()).toHaveLength(0);await page.screenshot({path:'../../out/browser-gallery-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Explore Iris'}).click();await page.getByRole('radio',{name:/Fine fibres/}).check();await page.getByRole('radio',{name:/Earth/}).check();await enter(page);await expect(page).toHaveURL(/\/explorations\//);await page.getByRole('link',{name:'Open image ↗',exact:true}).first().focus();await four(page);await expect(page.getByRole('link',{name:'Open image ↗',exact:true}).first()).toBeFocused();
 await expect(page.locator('.direction-strip')).toContainText('Fine fibres');await expect(page.locator('.direction-strip')).toContainText('Earth');await expect(page.locator('.direction-strip img')).toHaveCount(2);
 await expect(page.locator('input[type=checkbox]')).toHaveCount(0);await expect(page.locator('main')).not.toContainText(/Try something different|Refresh samples|Earlier batches|Keep what you found|session|saved on this device/i);await expect(page.getByRole('button',{name:/Generate|similar/})).toHaveCount(0);
 const gridURL=page.url();await page.getByRole('button',{name:'Add to favourites'}).first().click();await expect(page).toHaveURL(gridURL);await expect(page.getByRole('button',{name:'Remove from favourites'})).toHaveCount(1);await page.screenshot({path:'../../out/browser-grid-desktop.png',fullPage:true});
 await page.route('**/downloads/*',async route=>{await new Promise(resolve=>setTimeout(resolve,5500));await route.continue();});await page.getByRole('link',{name:'Open image ↗',exact:true}).nth(1).click();await expect(page).toHaveURL(/\/samples\//);await expect(page.getByRole('button',{name:'Add to favourites'})).toBeVisible();
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.shareProof={active:navigator.userActivation.isActive,count:data.files.length,size:data.files[0].size}}});});
 await expect(page.getByRole('button',{name:'Share image',exact:true})).toBeEnabled({timeout:15000});await page.getByRole('button',{name:'Share image',exact:true}).click();const proof=await page.evaluate(()=>window.shareProof);expect(proof.active).toBe(true);expect(proof.count).toBe(1);expect(proof.size).toBeGreaterThan(1000);await page.unroute('**/downloads/*');
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download image',exact:true}).click();const download=await downloading;const bytes=await fs.readFile(await download.path());expect(bytes.subarray(1,4).toString()).toBe('PNG');expect(bytes.readUInt32BE(16)).toBe(1200);expect(bytes.readUInt32BE(20)).toBe(1200);await page.screenshot({path:'../../out/browser-detail-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Generate similar ones'}).click();await four(page);await page.getByRole('link',{name:'Favourites',exact:true}).click();await expect(page.locator('.favourites-grid .sample')).toHaveCount(1);await page.getByRole('link',{name:'Open Iris favourite'}).click();await expect(page).toHaveURL(/\/samples\//);const detailURL=page.url();await page.getByRole('button',{name:'Remove from favourites'}).click();await expect(page).toHaveURL(detailURL);await page.getByRole('link',{name:'Favourites',exact:true}).click();await expect(page.getByText('See something you love?')).toBeVisible();expect(errors).toEqual([]);
});
test('no-JavaScript automatically reveals four images and retains ordinary download forms',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844},baseURL});const page=await context.newPage();await page.goto('/art/pools');await enter(page);await four(page);await page.screenshot({path:'../../out/browser-grid-mobile-nojs.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Add to favourites'}).first().click();await page.getByRole('link',{name:'Open image ↗',exact:true}).first().click();await page.getByRole('button',{name:'Prepare download',exact:true}).click();await expect(page.getByRole('link',{name:'Download image',exact:true})).toBeVisible({timeout:60000});const downloading=page.waitForEvent('download');await page.getByRole('link',{name:'Download image',exact:true}).click();expect((await downloading).suggestedFilename()).toMatch(/\.png$/);await context.close();
});
test('favourites form one simple page across art forms on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/art/foam');await enter(page);await four(page);await page.getByRole('button',{name:'Add to favourites'}).first().click();await page.goto('/art/iris');await enter(page);await four(page);await page.getByRole('button',{name:'Add to favourites'}).first().click();await page.getByRole('link',{name:'Favourites',exact:true}).click();await expect(page.locator('.favourites-grid .sample')).toHaveCount(2);await expect(page.getByRole('link',{name:'Open Foam favourite'})).toBeVisible();await expect(page.getByRole('link',{name:'Open Iris favourite'})).toBeVisible();await page.screenshot({path:'../../out/browser-favourites-mobile.png',fullPage:true});await page.getByRole('button',{name:'Remove from favourites'}).first().click();await expect(page).toHaveURL(baseURL+'/favourites');await expect(page.locator('.favourites-grid .sample')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
