// Command genqqlpalettes generates internal/sketch/qql/palettes.go from the
// QQL colour dataset in docs/reference/qql-colordata.json.
// Run from the repo root: go run ./tools/genqqlpalettes
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
)

type wireColor struct {
	Name string `json:"name"`

	Hue         float64 `json:"hue"`
	HueMin      float64 `json:"hueMin"`
	HueMax      float64 `json:"hueMax"`
	HueVariance float64 `json:"hueVariance"`

	Sat         float64 `json:"sat"`
	SatMin      float64 `json:"satMin"`
	SatMax      float64 `json:"satMax"`
	SatVariance float64 `json:"satVariance"`

	Bright         float64 `json:"bright"`
	BrightMin      float64 `json:"brightMin"`
	BrightMax      float64 `json:"brightMax"`
	BrightVariance float64 `json:"brightVariance"`
}

// A background entry is a positional triple: name, weight, substitutions.
// A null substitution target means "drop this colour from the sequence".
type wireBackground struct {
	Name   string
	Weight float64
	Subs   map[string]*string
}

func (b *wireBackground) UnmarshalJSON(data []byte) error {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if len(raw) != 3 {
		return fmt.Errorf("background entry has %d fields, want 3", len(raw))
	}
	if err := json.Unmarshal(raw[0], &b.Name); err != nil {
		return err
	}
	if err := json.Unmarshal(raw[1], &b.Weight); err != nil {
		return err
	}
	return json.Unmarshal(raw[2], &b.Subs)
}

type wireSplatter struct {
	Name   string
	Weight float64
}

func (s *wireSplatter) UnmarshalJSON(data []byte) error {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if len(raw) != 2 {
		return fmt.Errorf("splatter entry has %d fields, want 2", len(raw))
	}
	if err := json.Unmarshal(raw[0], &s.Name); err != nil {
		return err
	}
	return json.Unmarshal(raw[1], &s.Weight)
}

type wirePalette struct {
	Name             string           `json:"name"`
	Swatches         []string         `json:"swatches"`
	ColorSeq         []string         `json:"colorSeq"`
	BackgroundColors []wireBackground `json:"backgroundColors"`
	SplatterColors   []wireSplatter   `json:"splatterColors"`
}

type wireDB struct {
	Colors   []wireColor   `json:"colors"`
	Palettes []wirePalette `json:"palettes"`
}

func main() {
	const src = "docs/reference/qql-colordata.json"
	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}
	var db wireDB
	if err := json.Unmarshal(raw, &db); err != nil {
		log.Fatal(err)
	}

	key := make(map[string]int, len(db.Colors))
	for i, c := range db.Colors {
		if _, dup := key[c.Name]; dup {
			log.Fatalf("duplicate colour %q", c.Name)
		}
		key[c.Name] = i
	}
	lookup := func(name string) int {
		i, ok := key[name]
		if !ok {
			log.Fatalf("undefined colour %q", name)
		}
		return i
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/genqqlpalettes from %s; DO NOT EDIT.\n\n", src)
	b.WriteString("package qql\n\n")
	b.WriteString(`import "github.com/jaminalder/go-graphics/internal/palette"` + "\n\n")

	b.WriteString("// qqlSwatches is QQL's colour material: every swatch is an HSB base with\n")
	b.WriteString("// a per-channel spread and a clamp box it may never leave.\n")
	b.WriteString("var qqlSwatches = []palette.Swatch{\n")
	for _, c := range db.Colors {
		fmt.Fprintf(&b, "\t{Name: %q, Base: palette.HSB{H: %s, S: %s, B: %s},\n",
			c.Name, num(c.Hue), num(c.Sat), num(c.Bright))
		fmt.Fprintf(&b, "\t\tHMin: %s, HMax: %s, HStd: %s,\n", num(c.HueMin), num(c.HueMax), num(c.HueVariance))
		fmt.Fprintf(&b, "\t\tSMin: %s, SMax: %s, SStd: %s,\n", num(c.SatMin), num(c.SatMax), num(c.SatVariance))
		fmt.Fprintf(&b, "\t\tBMin: %s, BMax: %s, BStd: %s},\n", num(c.BrightMin), num(c.BrightMax), num(c.BrightVariance))
	}
	b.WriteString("}\n\n")

	b.WriteString("// qqlPalettes are the seven city palettes, keyed by trait value.\n")
	b.WriteString("var qqlPalettes = map[string]colorSet{\n")
	for _, p := range db.Palettes {
		fmt.Fprintf(&b, "\t%q: {\n\t\tName: %q,\n", p.Name, p.Name)

		seq := make([]string, len(p.ColorSeq))
		for i, n := range p.ColorSeq {
			seq[i] = fmt.Sprint(lookup(n))
		}
		fmt.Fprintf(&b, "\t\tSeq: []swatchKey{%s},\n", strings.Join(seq, ", "))

		b.WriteString("\t\tBackgrounds: []bgChoice{\n")
		for _, bg := range p.BackgroundColors {
			fmt.Fprintf(&b, "\t\t\t{Color: %d, Weight: %s", lookup(bg.Name), num(bg.Weight))
			if len(bg.Subs) > 0 {
				names := make([]string, 0, len(bg.Subs))
				for n := range bg.Subs {
					names = append(names, n)
				}
				sort.Strings(names)
				var subs []string
				for _, n := range names {
					target := "dropSwatch"
					if to := bg.Subs[n]; to != nil {
						target = fmt.Sprint(lookup(*to))
					}
					subs = append(subs, fmt.Sprintf("%d: %s", lookup(n), target))
				}
				fmt.Fprintf(&b, ", Subs: map[swatchKey]swatchKey{%s}", strings.Join(subs, ", "))
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t\t},\n")

		b.WriteString("\t\tSplatter: []weightedSwatch{")
		var spl []string
		for _, s := range p.SplatterColors {
			spl = append(spl, fmt.Sprintf("{%d, %s}", lookup(s.Name), num(s.Weight)))
		}
		fmt.Fprintf(&b, "%s},\n", strings.Join(spl, ", "))

		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	if len(db.Colors) < 100 || len(db.Palettes) != 7 {
		log.Fatalf("parsed %d colours and %d palettes; data format drifted?",
			len(db.Colors), len(db.Palettes))
	}
	const out = "internal/sketch/qql/palettes.go"
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil { //nolint:gosec // generated source
		log.Fatal(err)
	}
	fmt.Printf("wrote %s with %d swatches and %d palettes\n", out, len(db.Colors), len(db.Palettes))
}

// num formats a float without a trailing ".0", so the generated table reads
// like the source data.
func num(v float64) string {
	if v == float64(int64(v)) {
		return fmt.Sprintf("%d", int64(v))
	}
	return fmt.Sprintf("%v", v)
}
